// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDco0pBLdP9cb5RUa63gmKYLnB1O45kBjk',
    appId: '1:885115401948:android:fdad8c0169924a7eb1a619',
    messagingSenderId: '885115401948',
    projectId: 'lightweaver-6af9c',
    storageBucket: 'lightweaver-6af9c.firebasestorage.app',

    // measurementId: 'G-HYLR3KGRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO0V8PFp_2pGyPyTCcEPjLI8Rkvvn-SCY',
    appId: '1:789212789329:android:a8e1fae929c7fadb3c1670',
    messagingSenderId: '789212789329',
    projectId: 'savoapp-41cbb',
    storageBucket: 'savoapp-41cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDco0pBLdP9cb5RUa63gmKYLnB1O45kBjk',
    appId: '1:885115401948:android:fdad8c0169924a7eb1a619',
    messagingSenderId: '885115401948',
    projectId: 'lightweaver-6af9c',
    storageBucket: 'lightweaver-6af9c.firebasestorage.app',
    iosClientId:
        '816831984722-rnmhv8pt2rrq4b3tpi1i6o72rddqo074.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAntonxBoilerplate',
  );
}
